"""Generate reports from analyzed results."""

import json
from collections import Counter, defaultdict
from typing import Dict, List

import pandas as pd


class ReportGenerator:
    """Generate actionable reports for CS teams."""
    
    def generate_report(self, analyzed_results: List[Dict]) -> str:
        """Generate markdown report."""
        # Calculate statistics
        total = len(analyzed_results)
        
        # Lane distribution
        lanes = Counter(r.get("lane", "UNKNOWN") for r in analyzed_results)
        understanding = lanes.get("UNDERSTANDING", 0)
        incident = lanes.get("INCIDENT", 0)
        spam = lanes.get("SPAM", 0)
        
        # Understanding queries breakdown
        understanding_queries = [r for r in analyzed_results if r.get("lane") == "UNDERSTANDING"]
        well_answered = len([r for r in understanding_queries 
                           if r.get("evaluation", {}).get("bucket") == "well_answered"])
        partial = len([r for r in understanding_queries 
                      if r.get("evaluation", {}).get("bucket") == "partial"])
        
        # Action items (only from partial understanding queries)
        action_items = [r for r in analyzed_results 
                       if r.get("lane") == "UNDERSTANDING" 
                       and r.get("evaluation", {}).get("bucket") == "partial"]
        
        doc_write = len([r for r in action_items if r.get("action") == "DOC_WRITE"])
        doc_update = len([r for r in action_items if r.get("action") == "DOC_UPDATE"])
        
        # Group by target article
        article_actions = defaultdict(list)
        for item in action_items:
            article = item.get("target_article", "Unknown")
            article_actions[article].append(item)
        
        # Sort by count
        sorted_articles = sorted(article_actions.items(), key=lambda x: -len(x[1]))
        
        # Build report
        report = f"""# RAGTriage Analysis Report

## Executive Summary

| Metric | Count | Percentage |
|--------|-------|------------|
| Total Queries | {total} | 100% |
| **UNDERSTANDING** | {understanding} | {understanding/total*100:.1f}% |
| **INCIDENT** | {incident} | {incident/total*100:.1f}% |
| **SPAM** | {spam} | {spam/total*100:.1f}% |

### Understanding Queries Breakdown

| Status | Count | Percentage |
|--------|-------|------------|
| Well Answered | {well_answered} | {well_answered/understanding*100:.1f}% |
| Partial Answer | {partial} | {partial/understanding*100:.1f}% |

### Action Items ({len(action_items)} total)

| Action | Count | Percentage |
|--------|-------|------------|
| Write New Article | {doc_write} | {doc_write/len(action_items)*100:.1f}% |
| Update Existing | {doc_update} | {doc_update/len(action_items)*100:.1f}% |

---

## Top Priority Articles

### Articles to Write ({doc_write})

"""
        
        # Articles to write
        write_articles = [(art, items) for art, items in sorted_articles 
                         if items[0].get("action") == "DOC_WRITE"]
        for article, items in write_articles[:10]:
            report += f"\n**{article}** ({len(items)} questions)\n"
            for item in items[:3]:
                report += f"- {item['query'][:100]}...\n"
            if len(items) > 3:
                report += f"- *...and {len(items) - 3} more*\n"
        
        report += f"\n### Articles to Update ({doc_update})\n\n"
        
        # Articles to update
        update_articles = [(art, items) for art, items in sorted_articles 
                          if items[0].get("action") == "DOC_UPDATE"]
        for article, items in update_articles[:10]:
            report += f"\n**{article}** ({len(items)} questions)\n"
            for item in items[:3]:
                report += f"- {item['query'][:100]}...\n"
            if len(items) > 3:
                report += f"- *...and {len(items) - 3} more*\n"
        
        report += """
---

## How to Use This Report

1. **Start with DOC_WRITE items** - These represent missing documentation
2. **Review DOC_UPDATE items** - Enhance existing articles with missing info
3. **Monitor INCIDENT queries** - These may indicate product issues

*Generated by RAGTriage*
"""
        
        return report
    
    def generate_csv(self, analyzed_results: List[Dict]) -> pd.DataFrame:
        """Generate CSV of action items."""
        rows = []
        
        for item in analyzed_results:
            eval_data = item.get("evaluation", {})
            scores = eval_data.get("scores", {})
            
            rows.append({
                "query": item.get("query", ""),
                "lane": item.get("lane", ""),
                "category": item.get("category", ""),
                "topic": item.get("topic", ""),
                "action": item.get("action", ""),
                "target_article": item.get("target_article", ""),
                "gap": item.get("gap", ""),
                "overall_score": eval_data.get("overall_score", 0),
                "correctness": scores.get("correctness", 0),
                "completeness": scores.get("completeness", 0),
                "context_usage": scores.get("context_usage", 0),
                "clarity": scores.get("clarity", 0),
                "conciseness": scores.get("conciseness", 0),
                "bucket": eval_data.get("bucket", ""),
                "generated_answer": item.get("generated_answer", "")[:200],
            })
        
        return pd.DataFrame(rows)
